server:
  port: 8081

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: package-service
  datasource:
    url: jdbc:postgresql://postgres:5432/funky-dev
    username: funky
    password: funky
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
 
resilience4j:
  ratelimiter:
    instances:
      funkyBreaker:
        timeout-duration: 5s 
        limit-refresh-period: 4s
        limit-for-period: 2
  circuitbreaker:
    instances:
      funkyBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        register-health-indicator: true
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-type: count_based
        
#read form env variable
qrcode:
  output:
    directory: "/Users/javierbarbieri/developer/packageservice"

funky-service:
  url: ${FUNKY_SERVICE_URL}