version: '3.8'
services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - funky-network
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: funky
      POSTGRES_PASSWORD: funky
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - funky-network
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - postgres:/data/postgres
    ports:
      - "5050:80"
    networks:
      - funky-network
    restart: unless-stopped

#  service-registry:
#    image: hjbarbieri/service-registry:latest
#    container_name: serviceregistry
#    ports:
#      - 8761:8761
#    depends_on:
#      - zipkin
#    networks:
#      - funky-network
#    environment:
#      - SPRING_PROFILES_ACTIVE=dev
#    restart: unless-stopped
#
#  config-server:
#    image: hjbarbieri/config-server:latest
#    container_name: configserver
#    ports:
#      - 8088:8088
#    depends_on:
#      - zipkin
#      - service-registry
#    networks:
#      - funky-network
#    environment:
#      - SPRING_PROFILES_ACTIVE=dev
#    restart: unless-stopped
#
#  funky-service:
#    image: hjbarbieri/funky-service:latest
#    container_name: funkyservice
#    ports:
#      - 8082:8082
#    depends_on:
#      - zipkin
#      - service-registry
#      - config-server
#    networks:
#      - funky-network
#    environment:
#      - SPRING_PROFILES_ACTIVE=dev
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka
#      - BASE_URL=https://api.tiendanube.com/v1/960238/orders
#      - AUTH_TOKEN=cff9f0ddd275f1e33e8487179dc4a3d6fe05fb80
#      - USER_AGENT=funky_prod (hj.barbieri@gmail.com)
#
#  package-service:
#    image: hjbarbieri/package-service:latest
#    container_name: packageservice
#    ports:
#      - 8081:8081
#    depends_on:
#      - zipkin
#      - postgres
#      - pgadmin
#      - config-server
#      - service-registry
#    networks:
#      - funky-network
#      - postgres
#    environment:
#      - SPRING_PROFILES_ACTIVE=dev
#      - FUNKY_SERVICE_URL=http://funkyservice:8082
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka
#      - JAVA_OPTS=-XX:MaxDirectMemorySize=25M -XX:MaxMetaspaceSize=200000K -XX:ReservedCodeCacheSize=400M -Xss1M
#    restart: unless-stopped
#
#  api-gateway:
#    image: hjbarbieri/api-gateway:latest
#    container_name: apigateway
#    ports:
#      - 8084:8084
#    depends_on:
#      - zipkin
#      - service-registry
#      - config-server
#    networks:
#      - funky-network
#    environment:
#      - SPRING_PROFILES_ACTIVE=dev
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka
#      - JAVA_OPTS=-XX:MaxDirectMemorySize=10M -XX:MaxMetaspaceSize=100000K -XX:ReservedCodeCacheSize=200M -Xss512K
#    restart: unless-stopped

networks:
  funky-network:
    driver: bridge
  postgres:
    driver: bridge

volumes:
  postgres:
  admin: