server:
  port: 8084

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: api-gateway
#  config:
#    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: funky-service
          uri: lb://FUNKY-SERVICE
          predicates:
            - Path=/funky/**
        - id: package-service
          uri: lb://PACKAGE-SERVICE
          predicates:
            - Path=/package/**
        - id: eureka-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/main
          filters:
            - SetPath=/
        - id: eureka-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

logging:
  level:
    root: info
    org:
      springframework:
        cloud:
          springframework:
            cloud:
              gateway: TRACE
              gateway.route.RouteDefinitionLocator: INFO


