spring:
  application:
    name: funky-service
  config:
    import: "optional:configserver:http://localhost:8088"
scheduler:
  email:
    cron: "0 26 7 * * ?" # Run every day at midnight
    #cron: "0 * * * * ?"