spring:
  application:
    name: funky-service

server:
  port: 8082

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/span
  tracing:
    sampling:
      probability: 1.0

configtn:
  base-url: ${BASE_URL}
  auth-token: ${AUTH_TOKEN}
  user-agent: ${USER_AGENT}