spring:
  application:
    name: funky-service
  config:
    import: "optional:configserver:http://localhost:8088"

configtn:
  base-url: ${BASE_URL}
  auth-token: ${AUTH_TOKEN}
  user-agent: ${USER_AGENT}