services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: funky
      POSTGRES_PASSWORD: funky
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - funky-network
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - postgres:/data/postgres
    ports:
      - "5050:80"
    networks:
      - funky-network
    restart: unless-stopped

networks:
  funky-network:
    driver: bridge

volumes:
  postgres:
  admin: