server:
  port: 8088

spring:
  profiles:
    active: native
  application:
    name: config-server

management:
  tracing:
    sampling:
      probability: 1.0
  #endpoints:
   # web:
    #  exposure:
     #   include: *