server:
  port: 8088

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HugojBarbieri/application-config/
  application:
    name: config-server-dev

management:
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://serviceregistry:8761/eureka/

