server:
  port: 8081

eureka:
  client:
    defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

#read form env variable
qrcode:
  output:
    directory: "/Users/javierbarbieri/developer/package-service"
